
const colors = {
    green: '#799283',
    hardGreen: '#135846',
    lightGreen: '#EBF1EF',
    red: '#E23428',
    lightRed: '#FFEDEC',
    light: '#B2B2B2',
    bgGray: '#F8F8F8',
    gray: '#6E6E6E',
    borderGray: '#D4D4D4',
    checkInBtnText: "#5AD07A",
    checkInBtnBgr: "#E8FFEE",
    checkOutBtnText: "#E23428",
    checkOutBtnBgr: "#FFEDEC",
    inProgressBtnText: "#6D6D6D",
    inProgressBtnBgr: "#E2E2E2",
    viewNotesBtnBgr:"#EEF9F2",
    bottomBorderGray: '#c5c5c5',
    white: 'white',
    yellow: '#FFFF4E',
    lightYellow: '#ffffcc',
    hardYellow: '#a4a403',
    lightViolet: '#eee6ff',
    hardViolet: '#884dff',
    redLess: "#e0564c",
    mattBlack: "#393939",
    phoneBtnBgr: '#E8F2EF',
  };
  
  export default colors;